sudo cp neustar-prod_12_2649.txt /fsx/neustar-failed/
sudo cp neustar-prod_15_370.txt /fsx/neustar-failed/
sudo cp neustar-prod_3_1595.txt /fsx/neustar-failed/
sudo cp neustar-prod_10_2515.txt /fsx/neustar-failed/
sudo cp neustar-prod_11_2773.txt /fsx/neustar-failed/
sudo cp neustar-prod_10_2492.txt /fsx/neustar-failed/
sudo cp neustar-prod_13_1734.txt /fsx/neustar-failed/
sudo cp neustar-prod_5_467.txt /fsx/neustar-failed/
sudo cp neustar-prod_4_1854.txt /fsx/neustar-failed/
sudo cp neustar-prod_15_430.txt /fsx/neustar-failed/
sudo cp neustar-prod_8_184.txt /fsx/neustar-failed/
sudo cp neustar-prod_2_264.txt /fsx/neustar-failed/
sudo cp neustar-prod_12_2605.txt /fsx/neustar-failed/
sudo cp neustar-prod_1_1300.txt /fsx/neustar-failed/
sudo cp neustar-prod_7_1490.txt /fsx/neustar-failed/
sudo cp neustar-prod_12_2602.txt /fsx/neustar-failed/
sudo cp neustar-prod_1_1355.txt /fsx/neustar-failed/
sudo cp neustar-prod_7_1542.txt /fsx/neustar-failed/
sudo cp neustar-prod_5_486.txt /fsx/neustar-failed/
sudo cp neustar-prod_6_2992.txt /fsx/neustar-failed/
sudo cp neustar-prod_3_1611.txt /fsx/neustar-failed/
sudo cp neustar-prod_10_2544.txt /fsx/neustar-failed/
sudo cp neustar-prod_9_581.txt /fsx/neustar-failed/
sudo cp neustar-prod_8_137.txt /fsx/neustar-failed/
sudo cp neustar-prod_6_2991.txt /fsx/neustar-failed/
sudo cp neustar-prod_10_2537.txt /fsx/neustar-failed/
sudo cp neustar-prod_8_172.txt /fsx/neustar-failed/
sudo cp neustar-prod_6_2962.txt /fsx/neustar-failed/
sudo cp neustar-prod_1_1376.txt /fsx/neustar-failed/
sudo cp neustar-prod_12_2627.txt /fsx/neustar-failed/
sudo cp neustar-prod_7_1505.txt /fsx/neustar-failed/
sudo cp neustar-prod_5_513.txt /fsx/neustar-failed/
sudo cp neustar-prod_13_1664.txt /fsx/neustar-failed/
sudo cp neustar-prod_8_126.txt /fsx/neustar-failed/
sudo cp neustar-prod_14_906.txt /fsx/neustar-failed/
sudo cp neustar-prod_6_2981.txt /fsx/neustar-failed/
sudo cp neustar-prod_5_538.txt /fsx/neustar-failed/
sudo cp neustar-prod_14_890.txt /fsx/neustar-failed/
sudo cp neustar-prod_8_144.txt /fsx/neustar-failed/
sudo cp neustar-prod_5_471.txt /fsx/neustar-failed/
sudo cp neustar-prod_2_187.txt /fsx/neustar-failed/
sudo cp neustar-prod_3_1573.txt /fsx/neustar-failed/
sudo cp neustar-prod_5_489.txt /fsx/neustar-failed/
sudo cp neustar-prod_8_111.txt /fsx/neustar-failed/
sudo cp neustar-prod_5_532.txt /fsx/neustar-failed/
sudo cp neustar-prod_15_453.txt /fsx/neustar-failed/
sudo cp neustar-prod_10_2565.txt /fsx/neustar-failed/
sudo cp neustar-prod_13_1683.txt /fsx/neustar-failed/
sudo cp neustar-prod_13_1699.txt /fsx/neustar-failed/
sudo cp neustar-prod_15_416.txt /fsx/neustar-failed/
sudo cp neustar-prod_8_102.txt /fsx/neustar-failed/
sudo cp neustar-prod_12_2623.txt /fsx/neustar-failed/
sudo cp neustar-prod_2_194.txt /fsx/neustar-failed/
sudo cp neustar-prod_3_1625.txt /fsx/neustar-failed/
sudo cp neustar-prod_7_1485.txt /fsx/neustar-failed/
sudo cp neustar-prod_5_535.txt /fsx/neustar-failed/
sudo cp neustar-prod_5_525.txt /fsx/neustar-failed/
sudo cp neustar-prod_3_1582.txt /fsx/neustar-failed/
sudo cp neustar-prod_5_509.txt /fsx/neustar-failed/
sudo cp neustar-prod_7_1528.txt /fsx/neustar-failed/
sudo cp neustar-prod_6_3018.txt /fsx/neustar-failed/
sudo cp neustar-prod_14_888.txt /fsx/neustar-failed/
sudo cp neustar-prod_15_431.txt /fsx/neustar-failed/
sudo cp neustar-prod_6_3009.txt /fsx/neustar-failed/
sudo cp neustar-prod_10_2563.txt /fsx/neustar-failed/
sudo cp neustar-prod_4_1920.txt /fsx/neustar-failed/
sudo cp neustar-prod_3_1607.txt /fsx/neustar-failed/
sudo cp neustar-prod_15_406.txt /fsx/neustar-failed/
sudo cp neustar-prod_11_2763.txt /fsx/neustar-failed/
sudo cp neustar-prod_7_1527.txt /fsx/neustar-failed/
sudo cp neustar-prod_14_910.txt /fsx/neustar-failed/
sudo cp neustar-prod_1_1378.txt /fsx/neustar-failed/
sudo cp neustar-prod_5_465.txt /fsx/neustar-failed/
sudo cp neustar-prod_9_603.txt /fsx/neustar-failed/
sudo cp neustar-prod_7_1482.txt /fsx/neustar-failed/
sudo cp neustar-prod_8_141.txt /fsx/neustar-failed/
sudo cp neustar-prod_5_540.txt /fsx/neustar-failed/
sudo cp neustar-prod_2_206.txt /fsx/neustar-failed/
sudo cp neustar-prod_14_885.txt /fsx/neustar-failed/
